export const DEFAULT_DATA_INGREDIENTS = [
  { id: '1', text: 'Aceite de maíz' },
  { id: '2', text: 'Aceite de oliva' },
  { id: '3', text: 'Aceite de soja' },
  { id: '4', text: 'Aceite de trufa' },
  { id: '5', text: 'Acelgas' },
  { id: '6', text: 'Agua gaseosa' },
  { id: '7', text: 'Agua mineral' },
  { id: '8', text: 'Aguacate' },
  { id: '9', text: 'Albaricoque' },
  { id: '10', text: 'Alcachofas' },
  { id: '11', text: 'Alitas de pollo' },
  { id: '12', text: 'Almejas' },
  { id: '13', text: 'Alubias' },
  { id: '14', text: 'Anchoa' },
  { id: '15', text: 'Arroz largo' },
  { id: '16', text: 'Arroz redondo' },
  { id: '17', text: 'Atún' },
  { id: '18', text: 'Atún en lata' },
  { id: '19', text: 'Bacalao' },
  { id: '20', text: 'Batatas' },
  { id: '21', text: 'Berenjena' },
  { id: '22', text: 'Besugo' },
  { id: '23', text: 'Boletus' },
  { id: '24', text: 'Bonito' },
  { id: '25', text: 'Boquerón' },
  { id: '26', text: 'Brócoli' },
  { id: '27', text: 'Caballa' },
  { id: '28', text: 'Calabacín' },
  { id: '29', text: 'Calabaza' },
  { id: '30', text: 'Calamar' },
  { id: '31', text: 'Camarón' },
  { id: '32', text: 'Caquis' },
  { id: '33', text: 'Caracoles' },
  { id: '34', text: 'Cebolla' },
  { id: '35', text: 'Cebolla caramelizada' },
  { id: '36', text: 'Cebolleta' },
  { id: '37', text: 'Cereales' },
  { id: '38', text: 'Cerezas' },
  { id: '39', text: 'Cerveza' },
  { id: '40', text: 'Cervezas' },
  { id: '41', text: 'Champiñones' },
  { id: '42', text: 'Chicharro' },
  { id: '43', text: 'Cigala' },
  { id: '44', text: 'Ciruela' },
  { id: '45', text: 'Coles' },
  { id: '46', text: 'Coles de Bruselas' },
  { id: '47', text: 'Coliflor' },
  { id: '48', text: 'Cordero' },
  { id: '49', text: 'Corvina' },
  { id: '50', text: 'Crema de leche' },
  { id: '51', text: 'Cuajada' },
  { id: '52', text: 'Dorada' },
  { id: '53', text: 'Escarola' },
  { id: '54', text: 'Espaguetis' },
  { id: '55', text: 'Espárragos' },
  { id: '56', text: 'Espinaca' },
  { id: '57', text: 'Filetes de cerdo' },
  { id: '58', text: 'Filetes de pavo' },
  { id: '59', text: 'Filetes de pollo' },
  { id: '60', text: 'Filetes de ternera' },
  { id: '61', text: 'Frambuesas' },
  { id: '62', text: 'Fresas' },
  { id: '63', text: 'Frijoles' },
  { id: '64', text: 'Gamba' },
  { id: '65', text: 'Garbanzos' },
  { id: '66', text: 'Granada' },
  { id: '67', text: 'Guisantes' },
  { id: '68', text: 'Habas' },
  { id: '69', text: 'Habichuelas' },
  { id: '70', text: 'Harina' },
  { id: '71', text: 'Helado' },
  { id: '72', text: 'Higos' },
  { id: '73', text: 'Hinojo' },
  { id: '74', text: 'Hongos' },
  { id: '75', text: 'Horchata' },
  { id: '76', text: 'Huevos' },
  { id: '77', text: 'Jamón serrano' },
  { id: '78', text: 'Jamón york' },
  { id: '79', text: 'Judías' },
  { id: '80', text: 'Kiwis' },
  { id: '81', text: 'Langostino' },
  { id: '82', text: 'Leche' },
  { id: '83', text: 'Leche de coco' },
  { id: '84', text: 'Lechuga' },
  { id: '85', text: 'Lenguado' },
  { id: '86', text: 'Lentejas' },
  { id: '87', text: 'Limón' },
  { id: '88', text: 'Lubina' },
  { id: '89', text: 'Macarrones' },
  { id: '90', text: 'Maíz' },
  { id: '91', text: 'Mandarina' },
  { id: '92', text: 'Mango' },
  { id: '93', text: 'Mantequilla' },
  { id: '94', text: 'Manzanas' },
  { id: '95', text: 'Mejillones' },
  { id: '96', text: 'Melocotones' },
  { id: '97', text: 'Melón' },
  { id: '98', text: 'Membrillo' },
  { id: '99', text: 'Merluza' },
  { id: '100', text: 'Mero' },
  { id: '101', text: 'Naranja' },
  { id: '102', text: 'Nata' },
  { id: '103', text: 'Nectarina' },
  { id: '104', text: 'Ostras' },
  { id: '105', text: 'Palometa' },
  { id: '106', text: 'Pan' },
  { id: '107', text: 'Pan de molde' },
  { id: '108', text: 'Pan rallado' },
  { id: '109', text: 'Panco' },
  { id: '110', text: 'Patatas' },
  { id: '111', text: 'Pejerrey' },
  { id: '112', text: 'Pepino' },
  { id: '113', text: 'Peras' },
  { id: '114', text: 'Percebes' },
  { id: '115', text: 'Pimiento amarillo' },
  { id: '116', text: 'Pimiento rojo' },
  { id: '117', text: 'Pimiento verde' },
  { id: '118', text: 'Piña' },
  { id: '119', text: 'Plátanos' },
  { id: '120', text: 'Pomelo' },
  { id: '121', text: 'Puerro' },
  { id: '122', text: 'Pulpo' },
  { id: '123', text: 'Queso' },
  { id: '124', text: 'Queso lonchas' },
  { id: '125', text: 'Rape' },
  { id: '126', text: 'Remolacha' },
  { id: '127', text: 'Rodaballo' },
  { id: '128', text: 'Salmón' },
  { id: '129', text: 'Salmón ahumado' },
  { id: '130', text: 'Sandía' },
  { id: '131', text: 'Sardina' },
  { id: '132', text: 'Sepia' },
  { id: '133', text: 'Setas' },
  { id: '134', text: 'Setas de cardo' },
  { id: '135', text: 'Setas de chopo' },
  { id: '136', text: 'Setas shiitake' },
  { id: '137', text: 'Sidra' },
  { id: '138', text: 'Soja' },
  { id: '139', text: 'Tomate' },
  { id: '140', text: 'Trucha' },
  { id: '141', text: 'Trufa' },
  { id: '142', text: 'Uvas' },
  { id: '143', text: 'Vieira' },
  { id: '144', text: 'Vino blanco' },
  { id: '145', text: 'Vino rosado' },
  { id: '146', text: 'Vino tinto' },
  { id: '147', text: 'Whisky' },
  { id: '148', text: 'Yogures' },
  { id: '149', text: 'Zanahoria' },
  { id: '150', text: 'Zumo de naranja' }
]
