export const ROUTE_NAME_RECIPES = 'Recipes'
export const ROUTE_NAME_INGREDIENTS = 'Ingredients'
export const ROUTE_NAME_FOODS = 'Foods'
export const ROUTE_NAME_WEEK_MENU = 'Week menu'
export const ROUTE_NAME_GROCERY_LIST = 'Grocery list'
