export const DELETE = 'Borrar'
export const CHECK = 'Marcar'
export const UNCHECK = 'Desmarcar'
export const RESET_MEALS = 'Restablecer las comidas'
export const EDIT = 'Editar'

export const DELETE_MESSAGE = '¿Quieres eliminar todos los casillas marcadas?'
export const CHECK_MESSAGE = '¿Quieres marcar todos los artículos?'
export const UNCHECK_MESSAGE = '¿Quieres desmarcar todos los artículos?'
export const RESET_MEALS_MESSAGE = '¿Quieres restablecer todas las comidas del menú de la semana?'

export const RECIPE_LONG_PRESS = 'Manten presionada la receta para añadir los ingredientes'
export const ADD_GROCERY_LIST = 'Añadir a la lista de compra'

export const WELCOME = 'Bienvenidx!'
export const HELP_ICON_EXPLANATION_1 = 'En algunas páginas encontrarás un '
export const HELP_ICON_EXPLANATION_2 = ' icono a la derecha del encabezado, donde podrás ver información sobre su funcionalidad.'
export const HAPPY_GROCERY = 'Feliz compra!'
export const NOT_SHOW_AGAIN = 'No volver a mostrar esta página'
export const CONTINUE = 'Continuar'

export const RECIPES_JSON = 'JSON de las recetas'
export const SHOW_WELCOME = 'Mostrar la página de bienvenida'
export const SHOW_HELP_ICON_1 = 'Mostrar el '
export const SHOW_HELP_ICON_2 = ' icono en el encabezado de las páginas'
export const APP_VERSION = 'Versión de aplicación'

export const RECIPE_NAME = 'Nombre de la receta'
export const INGREDIENTS = 'Ingredientes'
export const PLUS_INGREDIENT = '+ Ingrediente'
export const NOTES = 'Notas'
export const SAVE = 'Guardar'

export const RECIPES = 'Recetas'
export const RECIPE_EDIT = 'Editar la receta'
export const WEEK_MENU = 'Menú'
export const GROCERY_LIST = 'Lista de la compra'
export const SETTINGS = 'Ajustes'
export const HELP = 'Ayuda!'

export const MONDAY = 'Lunes'
export const TUESTDAY = 'Martes'
export const WEDNESDAY = 'Miércoles'
export const THURSDAY = 'Jueves'
export const FRIDAY = 'Viernes'
export const SATURDAY = 'Sábado'
export const SUNDAY = 'Domingo'

export const LUNCH = 'Comida'
export const DINNER = 'Cena'

export const HOW_TO_ADD_NEW_RECIPE = '\u2023 Para AÑADIR una nueva receta, presiona el botón inferior derecho:'
export const HOW_TO_EDIT_RECIPE = '\u2023 Para EDITAR una receta, pulse sobre ella:'
export const HOW_TO_DELETE_RECIPE = '\u2023 Para ELIMINAR una receta, presione y arrastre hacia la derecha:'
export const HOW_TO_CHANGE_LUNCH_DINNER = '\u2023 Para CAMBIAR entre comida y cena:'
export const HOW_TO_SELECT_RECIPE = '\u2023 Para SELECCIONAR una receta para la comida actual:'
export const HOW_TO_ADD_INGREDIENTS_GROCERY_LIST = '\u2023 Para AÑADIR los ingredientes de las comidas a la lista de la compra:'
