export const DELETE = 'Delete'
export const CHECK = 'Check'
export const UNCHECK = 'Uncheck'
export const RESET_MEALS = 'Reset meals'
export const EDIT = 'Edit'

export const DELETE_MESSAGE = 'Do you want to delete all checked items?'
export const CHECK_MESSAGE = 'Do you want to check all items?'
export const UNCHECK_MESSAGE = 'Do you want to uncheck all items?'
export const RESET_MEALS_MESSAGE = 'Do you want to reset all week menu meals?'

export const RECIPE_LONG_PRESS = 'Long press on recipe to add the ingredients'
export const ADD_GROCERY_LIST = 'Add to grocery list'

export const WELCOME = 'Welcome!'
export const HELP_ICON_EXPLANATION_1 = 'In some pages you will find a '
export const HELP_ICON_EXPLANATION_2 = ' in the right of the header, where you will find some info about the functionality.'
export const HAPPY_GROCERY = 'Happy grocery shopping!'
export const NOT_SHOW_AGAIN = 'Do not show this page again'
export const CONTINUE = 'Continue'

export const RECIPES_JSON = 'Recipes JSON'
export const SHOW_WELCOME = 'Show welcome page'
export const SHOW_HELP_ICON_1 = 'Show the '
export const SHOW_HELP_ICON_2 = ' in pages header'
export const APP_VERSION = 'App version'

export const RECIPE_NAME = 'Recipe name'
export const INGREDIENTS = 'Ingredients'
export const PLUS_INGREDIENT = '+ Ingredient'
export const NOTES = 'Notes'
export const SAVE = 'Save'

export const RECIPES = 'Recipes'
export const RECIPE_EDIT = 'Recipe edit'
export const WEEK_MENU = 'Menu'
export const GROCERY_LIST = 'Grocery list'
export const SETTINGS = 'Settings'
export const HELP = 'Help!'

export const MONDAY = 'Monday'
export const TUESTDAY = 'Tuesday'
export const WEDNESDAY = 'Wednesday'
export const THURSDAY = 'Thursday'
export const FRIDAY = 'Friday'
export const SATURDAY = 'Saturday'
export const SUNDAY = 'Sunday'

export const LUNCH = 'Lunch'
export const DINNER = 'Dinner'

export const HOW_TO_ADD_NEW_RECIPE = '\u2023 To ADD a new recipe press the bottom right button:'
export const HOW_TO_EDIT_RECIPE = '\u2023 To EDIT a recipe, press on it:'
export const HOW_TO_DELETE_RECIPE = '\u2023 To DELETE a recipe, press and drag to the right:'
export const HOW_TO_CHANGE_LUNCH_DINNER = '\u2023 To CHANGE between lunch and dinner:'
export const HOW_TO_SELECT_RECIPE = '\u2023 To SELECT a recipe for the current meal:'
export const HOW_TO_ADD_INGREDIENTS_GROCERY_LIST = '\u2023 To ADD the ingredients of the meals to the grocery list:'
